train: dataset/images/train
val: dataset/images/val

# 클래스 개수
nc: 29

# 클래스 이름
names:
  - 계산기
  - 마우스
  - 보조배터리
  - 무선이어폰
  - 스마트워치
  - 노트북
  - 태블릿펜
  - 태블릿
  - 무선헤드폰
  - USB메모리
  - 휴대폰
  - 무선이어폰크래들
  - 반지
  - 팔찌
  - 목걸이
  - 귀걸이
  - 아날로그손목시계
  - 연필
  - 볼펜
  - 지우개
  - 필통
  - 샤프
  - 커터칼
  - 샤프심통
  - 자
  - 안경
  - 캡/야구 모자
  - 백팩
  - 지갑
